name: Release

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set Current Time
        uses: 1466587594/get-current-time@v1
        id: current-time
        with:
          format: YYYY.MM
          utcOffset: "+09:00"
        if: always()

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish
        env:
          VERSION: "${{ steps.current-time.outputs.formattedTime }}.${{github.run_number}}"
          USERNAME: ${{secrets.USERNAME}}
          TOKEN: ${{secrets.TOKEN}}
        run: ./gradlew publish